### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by kpcyrd** [gnzlbg/cargo-asm#12]
hey, I'm trying to package cargo-asm. :) I've noticed there are currently no tags for releases, would you mind tagging them on github? You don't need to tag every past release, I only need the latest release and a tag for each new release. Thanks! :)

**Comment by gnzlbg** [comment]
@kpcyrd would it work for you if I do a new "tagged" release?

**Comment by kpcyrd** [comment]
@gnzlbg yes, that would work for me. :) If everything works correctly it shows up here:

https://github.com/gnzlbg/cargo-asm/releases

**Comment by gnzlbg** [comment]
Done: https://github.com/gnzlbg/cargo-asm/releases/tag/v0.1.11

**Comment by gnzlbg** [comment]
Let me know if that works :)

**Comment by kpcyrd** [comment]
Awesome, thanks! :)

https://aur.archlinux.org/packages/cargo-asm/

**Comment by kpcyrd** [comment]
Hey, just a friendly bump, there is currently no tag for 0.1.16 :)
