### ISSUE TITLE
Support for --features

### ISSUE THREAD

**Issue by glandium** [gnzlbg/cargo-asm#14]
Sometimes functions are behind features, and it would be useful if cargo asm allowed to enable them.

**Comment by gnzlbg** [comment]
I’ll take a look at implementing this. In the meantime you can use
RUSTFLAGS to enable them :)

**Comment by glandium** [comment]
In case that helps, `cargo expand` supports --features, so you may want to look how it does it.

**Comment by gnzlbg** [comment]
Thanks! cargo asm just calls cargo directly so allowing features should be
as easy as just forwarding them.

**Comment by gnzlbg** [comment]
@glandium I've published v0.1.12 which let's you pass `--features` as usual :) 

Let me know if it works for you!
