### ISSUE TITLE
fix travis and appveyor builds

### ISSUE THREAD

**Issue by petr-tik** [gnzlbg/cargo-asm#28]
## Problem description

Commits on master aren't building on both CI runners, which makes it hard:
to reliably add new features
solve existing bugs
promote the tool to the rest of the community

I think we should fix CI before we continue developing it further.

## possible causes

cargo test failing

happy to pick up and investigate, if you can give me a couple of pointers

**Comment by gnzlbg** [comment]
Closed by #47 - the appveyor part is superseded by #48
