### ISSUE TITLE
Find a way to test without depending on compiler internals 

### ISSUE THREAD

**Issue by petr-tik** [gnzlbg/cargo-asm#32]
## Problem description

If I understand correctly, one of the reasons `cargo test` fails is the diff between expected asm output and what rust and llvm output every time local or Travis tests are run. The last version of rust specified in .travis.yml was 1.25, which is already behind stable. Since then llvm and rustc seemed to have changed their emit asm results (some `push`, `pop` and `mov` instructions are no longer generated). 

## Ideas/suggestions to solve

- Agree on a version of Rust that we promise to support (nightly and later change to Rust 2018)?
- Add unit tests to modules
- temporarily mark cli tests as allowed to fail (not a great idea long-term though) or remove them altogether

**Comment by gnzlbg** [comment]
> Agree on a version of Rust that we promise to support (nightly and later change to Rust 2018)?

Every rust compiler version changes the output of its assembly. The same will be true for Rust 2018 (stability with respect to generated assembly is a concept that doesn't really make sense.

This means that every nightly version changes the output of its assembly, therefore, we cannot test against nightly without more man power to update the tests. 

travis-ci tracks a somewhat recent stable (currently 1.25.0). We could update to a more recent one, but that requires updating all the tests. Feel free to send a PR, but that probably is only worth doing when one is preparing for submitting other changes.

-- 

So I am closing this as not actionable. Allowing the tests to fail is equivalent to not testing, and the only actionable suggestion seems to be to test against a particular version of the toolchain, and that's what we are already doing anyways.
