### ISSUE TITLE
How to find generic function?

### ISSUE THREAD

**Issue by velvia** [gnzlbg/cargo-asm#89]
Hi, thanks for this crate.  It works for simple non generic functions, but for generic functions it fails.

```
[ERROR]: could not find function at path "unpack" in the generated assembly.

Tips:
* make sure that the function is present in the final binary (e.g. if it's a generic function, make sure that it is actually monomorphized)
```

How do I find the monomorphized name of a function that is generic?  Thanks.

**Comment by gnzlbg** [comment]
Generics do not generate any code unless you use them, and when you do, they generate code only for the types used. So what you need to do is make sure that the generic function is monomorphized. 

If that is already the case, when you write the function names `cargo-asm` should give you some suggestions. Typically, the monomorphized names are the same that you use to call the function when passing explicit parameters, e.g., for `fn foo<T, U>(T) -> U;` when called with `T=i32` and `U=f32` it would be `foo::<i32,f32>`.

**Comment by velvia** [comment]
@gnzlbg what if I use them in bench or tests?    It's a library that I have, and I don't want to create special methods just to see the assembly.
Nice pix of snow btw.

**Comment by velvia** [comment]
I created another method and am able to see the disassembly.  However, I wonder if there is some way to have `cargo asm` parse the output of the bench or test targets, this would offer more flexibility for libraries.

**Comment by gnzlbg** [comment]
> what if I use them in bench or tests?

That's not supported yet, PR's welcome: https://github.com/gnzlbg/cargo-asm/issues/21
